config/routes.rb
Rails.application.routes.draw do

  root to: 'displays#home_page'

  resources :contents do
    member do
      get :delete 
    end
  end

  get 'display_type_content/:id', to: 'displays#display_type_content', as: :list_contents

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	has_many :seasons, inverse_of: :content
  accepts_nested_attributes_for :seasons, reject_if: :all_blank, allow_destroy: true
  
	scope :content_types_list, lambda {where.not(content_type: nil).pluck(:content_type).uniq}
end

app/models/episode.rb
class Episode < ApplicationRecord
	belongs_to :season
end

app/models/season.rb
class Season < ApplicationRecord
	belongs_to :content
	has_many :episodes, inverse_of: :season
  accepts_nested_attributes_for :episodes, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[show edit update destroy delete]

  def index
    @contents = Content.all
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to contents_path, notice: 'Content created successfully'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @content.update(content_params)
      redirect_to @content, notice: 'Content updated successfully'
    else
      render :edit
    end 
  end

  def delete; end

  def destroy
    @content.destroy
    redirect_to contents_path, notice: "Content #{@content.name} deleted successfully"
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end

  def content_params
    params.require(:content).permit(:name, :description, :certificate, :genre,
                                    :content_type, :with_seasons,
                                    seasons_attributes: [:id, :name, :description, :certificate,
                                    episodes_attributes: [:id, :name, :description]])
  end
end

app/controllers/displays_controller.rb
class DisplaysController < ApplicationController
  def home_page
    @content_types = Content.pluck(:content_type).uniq
  end

  def display_type_content
    @type_lists = Content.where(content_type: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper

	def certificates
		%w[U UA AS]
	end
	
end

app/views/contents/_episode_fields.html.erb
<div class='nested-fields', id='episodes-nested-form'>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <%= link_to_remove_association "remove episode", f %>
</div>

</table>

app/views/contents/_form.html.erb
<table summary="content form fields">
  <tr>
    <th></th>
    <td><%= form.select :content_type, Content.content_types_list + ['Add a new type'], {:include_blank => 'Please select a type', class: "types"} %></td>
  </tr>
  <tr class="add-type">
    <th>Type</th>
    <td><%= form.text_field :content_type, {class: "add-type-new"} %> </td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= form.text_field :name, required: true %> </td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= form.text_field :description %></td>
  </tr>
  <tr>
    <th>Certificate</th>
    <td><%= form.text_field :certificate %></td>
  </tr>
  <tr>
    <th>Genre</th>
    <td><%= form.text_field :genre %></td>
  </tr>
  <tr>
    <th>Has Seasons</th>
    <td><%= form.check_box :with_seasons, {class: "has_season"} %></td>
  </tr>
  <tr id= "season-area">
    <td>
      <h3>Seasons</h3>
      <div id='seasons'>
        <%= form.fields_for :seasons do |season| %>
          <%= render 'season_fields', :form => season %>
        <% end %>
        <div class='links'>
          <%= link_to_add_association 'add season', form, :seasons %>
        </div>
      </div>
    </td>
  <tr>
</table>

app/views/contents/_season_fields.html.erb
<div class='nested-fields', id='seasons-nested-form'>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :certificate %>
    <%= f.text_field :certificate %>
  </div>
  <%= link_to_remove_association "remove season", f %>

  <h3>Episodes</h3>
    <div id='episodes'>
      <%= f.fields_for :episodes do |episode| %>
        <%= render 'episode_fields', :f => episode %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association 'add episode', f, :episodes %>
      </div>
    </div>
</div>

app/views/contents/delete.html.erb
<%= link_to('Back', contents_path, class: 'back-link') %>

<div class="contents delete">
	<h2>Delete content</h2>
	<%= form_for(@content, method: 'delete') do |form| %>
		<p>Are you sure you want ot delete this content?</p>
		<p class="reference-name"><%= form.object.name %></p>
		<div class="form-buttons">
			<%= form.submit('Delete content') %>
		</div>
	<% end %>
</div>

app/views/contents/edit.html.erb
<div>
  <h2>Edit a Content</h2>

  <%= form_for(@content) do |form| %>
    
    <%= render(partial: 'form', locals: {form: form}) %>
    <div class="form-buttons">
      <%= form.submit('Update content') %>
    </div>
  <% end %>
</div>

app/views/contents/index.html.erb
<%= link_to('Add new', new_content_path, class: 'action new') %>

<% if @contents.present? %> 
  <div class='contents index'>
  	<h1>Listing contents</h1>
  </div>


  <table class='listing' summary="content list">
    <thead>
      <tr class='header'>
        <th>Name</th>
        <th>Description</th>
        <th>Certificate</th>
        <th>Genre</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @contents.each do |content| %>
        <tr>
          <td><%= content.name %></td>
          <td><%= content.description %></td>
          <td><%= content.certificate %></td>
          <td><%= content.genre %></td>
          <td class="actions">
            <%= link_to('show', content_path(content), class: 'action show') %>
            <%= link_to('edit', edit_content_path(content), class: 'action edit') %>
            <%= link_to('delete', delete_content_path(content), class: 'action delete') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
<% else %>
  <h3> No content available to display! Please create any!</h3>
<% end %>

app/views/contents/new.html.erb
<div>
  <h2>Create a Content</h2>

  <%= form_for(@content) do |form| %>
    
    <%= render(partial: 'form', locals: {form: form}) %>
    <div class="form-buttons">
      <%= form.submit('Create content') %>
    </div>
  <% end %>
</div>

app/views/contents/show.html.erb
<%= link_to('Back', contents_path, class: 'back-link') %>

<div class="contents show">
	<h2><%= @content.name.upcase %> Details</h2>
	<table summary="content detail view">
  <tr>
    <th>Name</th>
    <td><%= @content.name %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @content.description %></td>
  </tr>
  <tr>
    <th>Certificate</th>
    <td><%= @content.certificate %></td>
  </tr>
  <tr>
    <th>Genre</th>
    <td><%= @content.genre %></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= @content.created_at %></td>
  </tr>
  <tr>
    <th>Updated at</th>
    <td><%= @content.updated_at %></td>
  </tr>
</table>
  <!-- Displaying season details -->
  <% if @content.seasons.present? %>
  <p class="attr-heading">Season Details</p>
    <% @content.seasons.each do |season| %>
      <table class="table-show">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Certificate</th>
        </tr>
        <tr>
          <td class="attributes"><%= season.name %></td>
          <td class="attributes"><%= season.description %></td>
          <td class="attributes"><%= season.certificate %></td>
        </tr>
      </table>
    

    <!-- Displaying Episodes Details -->
    <% if season.episodes.present? %>
    <p class="attr-heading">Episodes Details</p>
      <% season.episodes.each do |episode| %>
        <table class="table-show">
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Certificate</th>
          </tr>
          <tr>
            <td class="attributes"><%= episode.name %></td>
            <td class="attributes"><%= episode.description %></td>
          </tr>
        </table>
    <% end %>
  <% end %>
<% end %>
<% end %>
</div>

app/views/contents/update.html.erb
<h1>Contents#update</h1>
<p>Find me in app/views/contents/update.html.erb</p>

app/views/displays/display_type_content.html.erb
<table class='listing' summary="content list">
  <thead>
    <tr class='header'>
      <th>Name</th>
      <th>Description</th>
      <th>Certificate</th>
      <th>Genre</th>
    </tr>
  </thead>

  <tbody >
    <% @type_lists.each do |content| %>
      <tr>
        <td><%= content.name %></td>
        <td><%= content.description %></td>
        <td><%= content.certificate %></td>
        <td><%= content.genre %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to "New content", new_content_path %>

app/views/displays/home_page.html.erb
<div>
	<h2>Squid DB</h2>

	<% @content_types.each do |a| %>
		<ul>
		  <li><%= link_to(a, list_contents_path(a), class: 'new content') %></li>
		</ul>
	<% end %>

	<%= link_to('Create a New Content', new_content_path, class: 'new content') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SquidDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>